### ISSUE TITLE
Something went wrong: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x1051a6a70>)

### ISSUE THREAD

**Issue by danstis** [danstis/PlexDownloader#2]
Hi,

I'm getting the below error now when I attempt to use PlexDownloader. This occurs with both shared and owned servers, both local and remote. Currently I'm running Plex Server 1.2.2.2857 and Mac OS Sierra

Something went wrong: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x1051a6a70>)
Traceback (most recent call last):
  File "PlexDownloader-master /plexdl.py", line 1062, in <module>
    x.search()
  File "PlexDownloader-master /plexdl.py", line 201, in search
    xmldoc = minidom.parse(urllib.urlopen(constructPlexUrl("/library/sections/"+unicode(self.plexid)+"/all")))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 689, in http_error_401
    errcode, errmsg, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 386, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x1051a6a70>)

Plex Download failed at 2016-10-21 18:18:20
Retrying in 600 Seconds...

**Comment by danstis** [comment]
You need to go into user.ini and change the MyPlex settings. You need to enable and add your username or email and your password. Speaking of which, @ilyaz, I don't like storing my password in plain-text, can we add that to a future upgrade?

In Plex, Server Settings, Network, may also need to set Required Connections to Preferred instead of Required.
