### ISSUE TITLE
Force sync on web interface causes error

### ISSUE THREAD

**Issue by danstis** [danstis/PlexDownloader#9]
When clicking the force search button on the web interface, the following error occurs:
![image](https://cloud.githubusercontent.com/assets/2137928/23098239/1c9b38a0-f695-11e6-8bfc-7ebb44d0115e.png)

In the log output the following error occurs:
`Force Searching TV Shows...
11 TV Shows Found in Your Wanted List...
Traceback (most recent call last):
  File "G:\Git_Repos\PlexDownloader\web\application.py", line 239, in process
    return self.handle()
  File "G:\Git_Repos\PlexDownloader\web\application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "G:\Git_Repos\PlexDownloader\web\application.py", line 462, in _delegate
    return handle_class(cls)
  File "G:\Git_Repos\PlexDownloader\web\application.py", line 438, in handle_class
    return tocall(*args)
  File "G:\Git_Repos\PlexDownloader\webui.py", line 204, in GET
    tvShowSearch()
  File "G:\Git_Repos\PlexDownloader\lib.py", line 253, in tvShowSearch
    website = urllib.urlopen(tvhttp)
  File "C:\Python27\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 457, in open_https
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "C:\Python27\lib\urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "C:\Python27\lib\urllib.py", line 691, in http_error_401
    errcode, errmsg, headers)
  File "C:\Python27\lib\urllib.py", line 386, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x00000000037BE808>)

127.0.0.1:59942 - - [19/Feb/2017 11:17:13] "HTTP/1.1 GET /force" - 500 Internal Server Error`

**Comment by danstis** [comment]
Still need to fix tv shows, the season folders are not specified.
